<?php
session_start();
unset($_SESSION["idusersUser"]);
unset($_SESSION["findayUser"]);
unset($_SESSION["prenomUser"]);
unset($_SESSION["nomUser"]);
unset($_SESSION["ddnUser"]);
unset($_SESSION["ddnlieuxUser"]);
unset($_SESSION["rayniterakaUser"]);
unset($_SESSION["renyniterakUser"]);
unset($_SESSION["cinUser"]);
unset($_SESSION["cindateUser"]);
unset($_SESSION["cinlieuxUser"]);
unset($_SESSION["saryUser"]);
unset($_SESSION["adiresyUser"]);
unset($_SESSION["asaataoUser"]);
unset($_SESSION["toeranaantranoUser"]);
unset($_SESSION["sexeUser"]);
unset($_SESSION["mdpUser"]);
unset($_SESSION["statutUser"]);
unset($_SESSION["idFokontanysUser"]);
unset($_SESSION["idsekteraUser"]);
unset($_SESSION["nomSecteurUser"]);
unset($_SESSION["nomDistrikasUser"]);
unset($_SESSION["nomFokontanysUser"]);
unset($_SESSION["nomKaomininasUser"]);
unset($_SESSION["nomFaritrasUser"]);

unset($_SESSION["pasipaoronumUser"]);
unset($_SESSION["pasipaorolieuxUser"]);
unset($_SESSION["pasipaorodelaiUser"]);

session_destroy();
header("location:connexion.php");